# Generated by Django 4.2.8 on 2024-01-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/', verbose_name='превью'),
        ),
    ]
