# Generated by Django 4.2.8 on 2025-07-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
